from pathlib import Path
from urllib.parse import quote

import streamlit as st

from answering import answer
from chunking import load_pdf_chunks
from indexing import index_chunks
from retrieval import list_manuals

DATA_FOLDER = Path("static")


def show_sources(hits):
    for number, hit in enumerate(hits, start=1):
        with st.expander(f"[{number}] {hit['source']}, page {hit['page']}"):
            st.link_button("Open PDF at this page", f"app/static/{quote(hit['source'])}#page={hit['page']}")
            st.text(hit["text"])


st.set_page_config(page_title="Manual Assistant")
st.title("Manual Assistant")
st.caption("Answers are generated by a local AI model and can be incomplete or wrong. Check important information, especially safety instructions, on the cited pages.")

uploaded = st.sidebar.file_uploader("Add a manual (PDF)", type="pdf")
if uploaded is not None and uploaded.name not in list_manuals():
    DATA_FOLDER.mkdir(exist_ok=True)
    pdf_path = DATA_FOLDER / uploaded.name
    pdf_path.write_bytes(uploaded.getbuffer())
    chunks = load_pdf_chunks(pdf_path)
    if not chunks:
        pdf_path.unlink()
        st.sidebar.error("This PDF contains no text; it may be scanned. Run OCR on it first, for example with ocrmypdf.")
    else:
        progress = st.sidebar.progress(0.0, text="Indexing...")
        index_chunks(
            chunks,
            lambda number, total: progress.progress(number / total, text=f"Indexing page {number} of {total}"),
        )
        progress.empty()
        st.sidebar.success(f"Added {uploaded.name}")

manuals = list_manuals()
if not manuals:
    st.info("Add a manual in the sidebar to start.")
    st.stop()

manual = st.sidebar.selectbox("Manual", manuals)

histories = st.session_state.setdefault("histories", {})
messages = histories.setdefault(manual, [])

for message in messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])
        show_sources(message.get("hits", []))

question = st.chat_input("Ask a question about this manual")
if question:
    with st.chat_message("user"):
        st.markdown(question)
    with st.chat_message("assistant"):
        with st.spinner("Searching the manual and writing an answer..."):
            text, hits = answer(question, manual)
        st.markdown(text)
        show_sources(hits)
        messages.append({"role": "user", "content": question})
        messages.append({"role": "assistant", "content": text, "hits": hits})